### ISSUE TITLE
enableMergePathsForKitKatAndAbove

### ISSUE THREAD

**Issue by po1arbear** [simolus3/fluttie#24] opened 2019-07-23 07:01 UTC
W/LOTTIE  (20331): Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().

**Comment by simolus3** [comment] 2019-07-23 07:07
Duplicate of #16

**Closed as completed by simolus3** 2019-07-23 07:07 UTC
